// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationSales.Infrastructure;

#nullable disable

namespace StationSales.Infrastructure.Migrations
{
    [DbContext(typeof(StationSalesDbContext))]
    [Migration("20260927175404_AddSourceSchedulingInterval")]
    partial class AddSourceSchedulingInterval
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("etl")
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StationSales.Domain.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SourceSystemId")
                        .HasColumnType("bigint");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SourceSystemId");

                    b.HasIndex("StationId");

                    b.ToTable("data_source", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.ExtractionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("PipelineDataSourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("RowsRead")
                        .HasColumnType("int");

                    b.Property<int>("RowsWritten")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("WindowFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "Status");

                    b.ToTable("extraction_run", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.Pipeline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("pipeline", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.PipelineDataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("IntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSuccessfulDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PipelineId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecoveryDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PipelineId", "DataSourceId")
                        .IsUnique();

                    b.ToTable("pipeline_data_source", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.PublishRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Checkpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RowsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("publish_run", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DocumentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("DocumentKeyHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastSeenExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentKeyHash")
                        .IsUnique();

                    b.ToTable("sale_document", "core");
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocumentDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DetailHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("DetailKeyHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastSeenExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("SaleDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SaleDocumentId", "DetailKeyHash")
                        .IsUnique();

                    b.ToTable("sale_document_detail", "core");
                });

            modelBuilder.Entity("StationSales.Domain.SourceSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("source_system", "etl");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "OPENCOMB",
                            IsActive = true,
                            Name = "OpenComb"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "GASOLUTION",
                            IsActive = true,
                            Name = "Gasolution"
                        });
                });

            modelBuilder.Entity("StationSales.Domain.Station", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BusinessRuc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("station", "etl");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_VENEZUELA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS VENEZUELA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_ICA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS ICA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_LA_MOLINA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS LA MOLINA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_VICTORIA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS VICTORIA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_VICTORIA_2",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS VICTORIA 2",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            BusinessRuc = "20511706361",
                            Code = "EDS_BARRANCO",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS BARRANCO",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_MARINA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS MARINA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_NUEVO_CHIMBOTE",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS NUEVO CHIMBOTE",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_ARGENTINA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS ARGENTINA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_CALLAO",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS CALLAO",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_CHINCHA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS CHINCHA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_PUENTE_PIEDRA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS PUENTE PIEDRA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_LURIN",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS LURIN",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_ATE",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS ATE",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_CHIMBOTE_2",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS CHIMBOTE 2",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_TRUJILLO",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS TRUJILLO",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17L,
                            BusinessRuc = "20516752310",
                            Code = "EDS_TOMAS_VALLE",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS TOMAS VALLE",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18L,
                            BusinessRuc = "20516752310",
                            Code = "EDS_CAMPOY",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS CAMPOY",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_VENEZUELA_2",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS VENEZUELA 2",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20L,
                            BusinessRuc = "20506151547",
                            Code = "EDS_PAITA",
                            CreatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EDS PAITA",
                            UpdatedAtUtc = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("DetailsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("DocumentsProcessed")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<long>("PipelineId")
                        .HasColumnType("bigint");

                    b.Property<int>("SoftDeletedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("transform_batch", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatchExtraction", b =>
                {
                    b.Property<long>("TransformBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExtractionRunId")
                        .HasColumnType("bigint");

                    b.HasKey("TransformBatchId", "ExtractionRunId");

                    b.ToTable("transform_batch_extraction", "etl");
                });

            modelBuilder.Entity("StationSales.Infrastructure.GasolutionStationSaleRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionRunId");

                    b.HasIndex("DataSourceId", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("gasolution_station_sale", "raw");
                });

            modelBuilder.Entity("StationSales.Infrastructure.OpenCombStationSaleRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ArtDescripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("art_descripcion");

                    b.Property<string>("At")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("at");

                    b.Property<string>("Caja")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("caja");

                    b.Property<string>("Cajero")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cajero");

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Codigo")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("codigo");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Dia")
                        .HasColumnType("datetime2")
                        .HasColumnName("dia");

                    b.Property<string>("Ebidata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ebidata");

                    b.Property<string>("Es")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("es");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaReplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_replicacion");

                    b.Property<int?>("FlgReplicacion")
                        .HasColumnType("int")
                        .HasColumnName("flg_replicacion");

                    b.Property<string>("Fpago")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("fpago");

                    b.Property<string>("Grupo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("grupo");

                    b.Property<decimal?>("Igv")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("igv");

                    b.Property<decimal?>("Importe")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("importe");

                    b.Property<decimal?>("Km")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("km");

                    b.Property<string>("Nombre")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("nombre");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("placa");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("precio");

                    b.Property<string>("Pump")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("pump");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("razon_social");

                    b.Property<decimal?>("RendiAcu")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("rendi_acu");

                    b.Property<decimal?>("RendiGln")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("rendi_gln");

                    b.Property<string>("Ruc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ruc");

                    b.Property<decimal?>("SolesKm")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("soles_km");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceTable")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("source_table");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tarjeta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tarjeta");

                    b.Property<string>("Td")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("td");

                    b.Property<string>("Text1")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("text1");

                    b.Property<string>("Tipo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("tipo");

                    b.Property<string>("Tm")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("tm");

                    b.Property<decimal?>("Trans")
                        .HasColumnType("decimal(14,0)")
                        .HasColumnName("trans");

                    b.Property<string>("Turno")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("turno");

                    b.Property<string>("Usr")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("usr");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionRunId");

                    b.HasIndex("DataSourceId", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("opencomb_station_sale", "raw");
                });

            modelBuilder.Entity("StationSales.Domain.DataSource", b =>
                {
                    b.HasOne("StationSales.Domain.SourceSystem", "SourceSystem")
                        .WithMany("DataSources")
                        .HasForeignKey("SourceSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StationSales.Domain.Station", "Station")
                        .WithMany("DataSources")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceSystem");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("StationSales.Domain.PipelineDataSource", b =>
                {
                    b.HasOne("StationSales.Domain.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationSales.Domain.Pipeline", "Pipeline")
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocumentDetail", b =>
                {
                    b.HasOne("StationSales.Domain.SaleDocument", null)
                        .WithMany("Details")
                        .HasForeignKey("SaleDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatchExtraction", b =>
                {
                    b.HasOne("StationSales.Domain.TransformBatch", null)
                        .WithMany("Extractions")
                        .HasForeignKey("TransformBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocument", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("StationSales.Domain.SourceSystem", b =>
                {
                    b.Navigation("DataSources");
                });

            modelBuilder.Entity("StationSales.Domain.Station", b =>
                {
                    b.Navigation("DataSources");
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatch", b =>
                {
                    b.Navigation("Extractions");
                });
#pragma warning restore 612, 618
        }
    }
}
