// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationSales.Infrastructure;

#nullable disable

namespace StationSales.Infrastructure.Migrations
{
    [DbContext(typeof(StationSalesDbContext))]
    [Migration("20260927054037_InitialCentralSchema")]
    partial class InitialCentralSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("etl")
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StationSales.Domain.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("data_source", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.ExtractionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("PipelineDataSourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("RowsRead")
                        .HasColumnType("int");

                    b.Property<int>("RowsWritten")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("WindowFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "Status");

                    b.ToTable("extraction_run", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.Pipeline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("pipeline", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.PipelineDataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSuccessfulDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PipelineId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecoveryDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PipelineId", "DataSourceId")
                        .IsUnique();

                    b.ToTable("pipeline_data_source", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.PublishRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Checkpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RowsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("publish_run", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DocumentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("DocumentKeyHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastSeenExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentKeyHash")
                        .IsUnique();

                    b.ToTable("sale_document", "core");
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocumentDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DetailHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("DetailKeyHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastSeenExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("SaleDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SaleDocumentId", "DetailKeyHash")
                        .IsUnique();

                    b.ToTable("sale_document_detail", "core");
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("DetailsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("DocumentsProcessed")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<long>("PipelineId")
                        .HasColumnType("bigint");

                    b.Property<int>("SoftDeletedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("transform_batch", "etl");
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatchExtraction", b =>
                {
                    b.Property<long>("TransformBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExtractionRunId")
                        .HasColumnType("bigint");

                    b.HasKey("TransformBatchId", "ExtractionRunId");

                    b.ToTable("transform_batch_extraction", "etl");
                });

            modelBuilder.Entity("StationSales.Infrastructure.GasolutionStationSaleRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionRunId");

                    b.HasIndex("DataSourceId", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("gasolution_station_sale", "raw");
                });

            modelBuilder.Entity("StationSales.Infrastructure.OpenCombStationSaleRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExtractionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionRunId");

                    b.HasIndex("DataSourceId", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("opencomb_station_sale", "raw");
                });

            modelBuilder.Entity("StationSales.Domain.PipelineDataSource", b =>
                {
                    b.HasOne("StationSales.Domain.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationSales.Domain.Pipeline", "Pipeline")
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocumentDetail", b =>
                {
                    b.HasOne("StationSales.Domain.SaleDocument", null)
                        .WithMany("Details")
                        .HasForeignKey("SaleDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatchExtraction", b =>
                {
                    b.HasOne("StationSales.Domain.TransformBatch", null)
                        .WithMany("Extractions")
                        .HasForeignKey("TransformBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StationSales.Domain.SaleDocument", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("StationSales.Domain.TransformBatch", b =>
                {
                    b.Navigation("Extractions");
                });
#pragma warning restore 612, 618
        }
    }
}
